// @ts-expect-error The OpenNext worker is generated by `npm run cf:build`.
import openNextWorker from "./.open-next/worker.js";

import { handleScheduledAttendance } from "./src/worker/scheduled";

export default {
  fetch: openNextWorker.fetch,
  scheduled(controller, env, context) {
    context.waitUntil(handleScheduledAttendance(controller, env));
  },
} satisfies ExportedHandler<CloudflareEnv>;
